file(GLOB_RECURSE APPLICATION_FILES ${CMAKE_CURRENT_LIST_DIR}/application/*.cpp)
file(GLOB_RECURSE COMPRESSION_FILES ${CMAKE_CURRENT_LIST_DIR}/compression/*.cpp)
file(GLOB_RECURSE EXCEPTIONS_FILES ${CMAKE_CURRENT_LIST_DIR}/exceptions/*.cpp)
file(GLOB_RECURSE JSON_FILES ${CMAKE_CURRENT_LIST_DIR}/json/*.cpp)
file(GLOB_RECURSE LOCALIZATION_FILES ${CMAKE_CURRENT_LIST_DIR}/localization/*.cpp)
file(GLOB_RECURSE LOGGING_FILES ${CMAKE_CURRENT_LIST_DIR}/logging/*.cpp)
file(GLOB_RECURSE MESSAGING_FILES ${CMAKE_CURRENT_LIST_DIR}/messaging/*.cpp)
file(GLOB NETWORK_FILES LIST_DIRECTORIES false ${CMAKE_CURRENT_LIST_DIR}/network/*.cpp)
file(GLOB_RECURSE POSIX_FILES ${CMAKE_CURRENT_LIST_DIR}/posix/*.cpp)
file(GLOB SECURITY_FILES LIST_DIRECTORIES false ${CMAKE_CURRENT_LIST_DIR}/security/*.cpp)
file(GLOB_RECURSE UTILS_FILES ${CMAKE_CURRENT_LIST_DIR}/utils/*.cpp)

if (NET_LIBCURL)
    file(GLOB CURL_FILES ${CMAKE_CURRENT_LIST_DIR}/network/curl/*.cpp)
    list(APPEND NETWORK_FILES ${CURL_FILES})
endif ()
if (NET_WPA_SUPPLICANT)
    file(GLOB WPA_SUPPLICANT_FILES ${CMAKE_CURRENT_LIST_DIR}/network/wpa_supplicant/*.cpp)
    list(APPEND NETWORK_FILES ${WPA_SUPPLICANT_FILES})
endif ()

if (GFX)
    file(GLOB_RECURSE GRAPHICS_FILES ${CMAKE_CURRENT_LIST_DIR}/graphics/*.cpp)
endif ()

if (OPENSSL_CRYPTO)
    file(GLOB CRYPTO_FILES ${CMAKE_CURRENT_LIST_DIR}/security/openssl/*.cpp)
    list(APPEND SECURITY_FILES ${CRYPTO_FILES})
elseif (MBEDTLS_CRYPTO)
    file(GLOB CRYPTO_FILES ${CMAKE_CURRENT_LIST_DIR}/security/mbedtls/*.cpp)
    list(APPEND SECURITY_FILES ${CRYPTO_FILES})
endif ()

set(LIBRARY_SOURCES
        ${CMAKE_CURRENT_LIST_DIR}/version.cpp
        ${APPLICATION_FILES}
        ${COMPRESSION_FILES}
        ${EXCEPTIONS_FILES}
        ${JSON_FILES}
        ${LOCALIZATION_FILES}
        ${LOGGING_FILES}
        ${MESSAGING_FILES}
        ${POSIX_FILES}
        ${SECURITY_FILES}
        ${UTILS_FILES}
        ${NETWORK_FILES}
        ${GRAPHICS_FILES}
)
mark_as_advanced(LIBRARY_SOURCES)